# Generated by Django 3.0.2 on 2020-01-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mobile',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
