# Generated by Django 3.0.2 on 2020-01-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_a',
            field=models.DateField(blank=True, null=True, verbose_name='place'),
        ),
    ]
