# Generated by Django 3.0.2 on 2020-01-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_a',
            field=models.DateField(blank=True, null=True, verbose_name='place'),
        ),
        migrations.AddField(
            model_name='student',
            name='date_b',
            field=models.DateField(blank=True, null=True, verbose_name='place'),
        ),
    ]
