# Generated by Django 3.0.2 on 2020-01-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200111_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='field_name',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
    ]
