# Generated by Django 3.0.2 on 2020-01-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_student_field_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date_a',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='field_name',
            new_name='image_profile',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='date_b',
            new_name='start_date',
        ),
    ]
